export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const ADD_PRODUCT_TO_CARD = 'ADD_PRODUCT_TO_CARD';
export const REMOVE_PRODUCT_FROM_CARD = 'REMOVE_PRODUCT_FROM_CARD';
